### ISSUE TITLE
How can we implement energy footprinting in the building-level

### ISSUE THREAD

**Issue by stephenxia** [PeterJWei/CitywideFootprinting#1]
Hi guys,

Great project. I'm interested in energy monitoring, but on the smaller scale (limited to just buildings). Is there a way we can scale this down for such an application?

Thanks,
Stephen

**Comment by PeterJWei** [comment]
For starters, we have a project

**Comment by PeterJWei** [comment]
For starters, you can check out our other github project:
https://github.com/Columbia-ICSL/EnergyFootprinting
We've published a few papers so far in BuildSys '16 and '17 about building energy at the building scale. If you have more specific questions, feel free to comment.
